<script type='text/javascript' src='http://code.jquery.com/jquery-1.11.3.min.js'></script>
<script type='text/javascript' src='assets/js/common.js'></script>
<script type='text/javascript' src='assets/js/constants.js'></script>
<script type='text/javascript' src='assets/js/track.js'></script>
<script type='text/javascript' src='assets/js/jquery-migrate.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.themepunch.tools.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.themepunch.revolution.min.js'></script>
<script type='text/javascript' src='assets/js/modernizr-2.7.1.min.js'></script>
<script type='text/javascript' src='assets/js/imagesloaded.pkgd.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.carouFredSel-6.2.1.js'></script>
<script type='text/javascript' src='assets/js/jquery.touchSwipe.min.js'></script>
<script type='text/javascript' src='assets/js/bootstrap.min.js'></script>
<script type='text/javascript' src='assets/js/hoverIntent-r7.min.js'></script>
<script type='text/javascript' src='assets/js/superfish-1.7.4.min.js'></script>
<script type='text/javascript' src='assets/js/main.js'></script>
<script type='text/javascript' src='assets/js/mediaelement-and-player.js'></script>
<script type='text/javascript' src='assets/js/player.js'></script>
<script type='text/javascript' src='assets/js/jquery.plugin.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.countdown.min.js'></script> 
<script type='text/javascript' src='assets/js/jquery.parallax.js'></script>
<script type='text/javascript' src='assets/js/owl.carousel.min.js'></script>